services:
 db:
  image: postgres:14.22-trixie
  container_name: db
  restart: always
  shm_size:  200mb
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: jobs
  ports:
   - 5432:5432
  volumes:
   - db_data:/var/lib/postgresql/data
volumes:
 db_data:
